# Generated by Django 4.2.23 on 2025-07-06 13:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FormulaType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="種類名"
                    ),
                ),
            ],
            options={
                "verbose_name": "論理式種類",
                "verbose_name_plural": "論理式種類",
            },
        ),
        migrations.CreateModel(
            name="InferenceRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="推論規則名")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
            ],
            options={
                "verbose_name": "推論規則",
                "verbose_name_plural": "推論規則",
            },
        ),
        migrations.CreateModel(
            name="LogicalFormula",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("representation", models.TextField(verbose_name="文字列表現(LaTeX)")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
            ],
            options={
                "verbose_name": "論理式",
                "verbose_name_plural": "論理式",
            },
        ),
        migrations.CreateModel(
            name="Proof",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence", models.IntegerField(verbose_name="連番")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
            ],
            options={
                "verbose_name": "証明",
                "verbose_name_plural": "証明",
            },
        ),
        migrations.CreateModel(
            name="ProofInference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence", models.IntegerField(verbose_name="連番")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "conclusion_formula",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.logicalformula",
                        verbose_name="結論論理式ID",
                    ),
                ),
                (
                    "from_nodes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="to_nodes",
                        to="core.proofinference",
                        verbose_name="先行する推論ステップ",
                    ),
                ),
                (
                    "inference_rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.inferencerule",
                        verbose_name="推論規則ID",
                    ),
                ),
                (
                    "proof",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.proof",
                        verbose_name="証明ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "証明推論",
                "verbose_name_plural": "証明推論",
                "unique_together": {("proof", "sequence")},
            },
        ),
        migrations.CreateModel(
            name="Theorem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.TextField(
                        blank=True, max_length=255, null=True, verbose_name="定理名"
                    ),
                ),
                (
                    "meaning",
                    models.TextField(blank=True, null=True, verbose_name="定理の意味"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "assumptions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="theorems_as_assumption",
                        to="core.logicalformula",
                        verbose_name="仮定論理式ID",
                    ),
                ),
                (
                    "conclusion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="theorems_as_conclusion",
                        to="core.logicalformula",
                        verbose_name="結論論理式ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "定理",
                "verbose_name_plural": "定理",
            },
        ),
        migrations.CreateModel(
            name="SymbolType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="種類名"
                    ),
                ),
                (
                    "is_quantifier",
                    models.BooleanField(default=False, verbose_name="量化記号かどうか"),
                ),
                (
                    "formula_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.formulatype",
                        verbose_name="論理式種類ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "記号種類",
                "verbose_name_plural": "記号種類",
            },
        ),
        migrations.CreateModel(
            name="Symbol",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="記号名")),
                ("arity", models.IntegerField(verbose_name="引数の数")),
                ("notes", models.TextField(blank=True, verbose_name="備考")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "argument_formula_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.formulatype",
                        verbose_name="引数の論理式種類ID",
                    ),
                ),
                (
                    "symbol_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.symboltype",
                        verbose_name="記号種類ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "記号",
                "verbose_name_plural": "記号",
            },
        ),
        migrations.AddField(
            model_name="proof",
            name="theorem",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.theorem",
                verbose_name="定理ID",
            ),
        ),
        migrations.AddField(
            model_name="inferencerule",
            name="result_formula",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="core.logicalformula",
                verbose_name="結論論理式ID",
            ),
        ),
        migrations.CreateModel(
            name="ProofUnresolvedAssumption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence", models.IntegerField(verbose_name="連番")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "added_by_inference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unresolved_assumptions_added",
                        to="core.proofinference",
                        verbose_name="導入した推論ステップ",
                    ),
                ),
                (
                    "formula",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.logicalformula",
                        verbose_name="仮定論理式ID",
                    ),
                ),
                (
                    "proof",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.proof",
                        verbose_name="証明ID",
                    ),
                ),
                (
                    "resolved_by_inference",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="unresolved_assumptions_resolved",
                        to="core.proofinference",
                        verbose_name="解消した推論ステップ",
                    ),
                ),
            ],
            options={
                "verbose_name": "証明未解消仮定",
                "verbose_name_plural": "証明未解消仮定",
                "unique_together": {("proof", "sequence")},
            },
        ),
        migrations.CreateModel(
            name="ProofInferenceArgument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence", models.IntegerField(verbose_name="連番")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "argument_formula",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.logicalformula",
                        verbose_name="引数論理式ID",
                    ),
                ),
                (
                    "proof_inference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.proofinference",
                        verbose_name="証明推論ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "証明推論引数",
                "verbose_name_plural": "証明推論引数",
                "unique_together": {("proof_inference", "sequence")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="proof",
            unique_together={("theorem", "sequence")},
        ),
        migrations.CreateModel(
            name="LogicalFormulaSymbol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence", models.IntegerField(verbose_name="連番")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "logical_formula",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="symbols",
                        to="core.logicalformula",
                        verbose_name="論理式ID",
                    ),
                ),
                (
                    "symbol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.symbol",
                        verbose_name="記号ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "論理式記号列",
                "verbose_name_plural": "論理式記号列",
                "unique_together": {("logical_formula", "sequence")},
            },
        ),
        migrations.CreateModel(
            name="InferenceRulePremise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence", models.IntegerField(verbose_name="連番")),
                (
                    "is_solvable_proposition_mandatory",
                    models.BooleanField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="解消可能命題の解消が必須かどうか",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "inference_rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.inferencerule",
                        verbose_name="推論規則ID",
                    ),
                ),
                (
                    "logical_formula",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inference_rule_premises_as_logical_formula",
                        to="core.logicalformula",
                        verbose_name="論理式ID",
                    ),
                ),
                (
                    "solvable_proposition",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inference_rule_premises_as_solvable_proposition",
                        to="core.logicalformula",
                        verbose_name="解消可能命題ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "推論規則仮定",
                "verbose_name_plural": "推論規則仮定",
                "unique_together": {("inference_rule", "sequence")},
            },
        ),
        migrations.CreateModel(
            name="InferenceRuleArgument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence", models.IntegerField(verbose_name="連番")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "inference_rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.inferencerule",
                        verbose_name="推論規則ID",
                    ),
                ),
                (
                    "symbol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.symbol",
                        verbose_name="記号ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "推論規則引数",
                "verbose_name_plural": "推論規則引数",
                "unique_together": {("inference_rule", "sequence")},
            },
        ),
    ]
